/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as campaignManagerSol from "./CampaignManager.sol";
export type { campaignManagerSol };
import type * as fherc20 from "./FHERC20";
export type { fherc20 };
import type * as fherc721 from "./FHERC721";
export type { fherc721 };
