/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { FhunderToken__factory } from "./FhunderToken__factory";
export { IFHERC20__factory } from "./IFHERC20__factory";
